<?php
/**
 * BrandNamesResponseTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  UBill\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * UBill API
 *
 * UBill API - provides programmatic access to our resources. You will be able to integrate our service into your system and communicate with clients easily.
 *
 * The version of the OpenAPI document: 2.1.7
 * Contact: info@ubill.ge
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace UBill\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * BrandNamesResponseTest Class Doc Comment
 *
 * @category    Class
 * @description BrandNamesResponse
 * @package     UBill\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BrandNamesResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "BrandNamesResponse"
     */
    public function testBrandNamesResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "statusID"
     */
    public function testPropertyStatusID()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "brands"
     */
    public function testPropertyBrands()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
