<?php
/**
 * SMSPayloadTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  UBill\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * UBill API
 *
 * UBill API - provides programmatic access to our resources. You will be able to integrate our service into your system and communicate with clients easily.
 *
 * The version of the OpenAPI document: 2.1.7
 * Contact: info@ubill.ge
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace UBill\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SMSPayloadTest Class Doc Comment
 *
 * @category    Class
 * @description SMSPayload
 * @package     UBill\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SMSPayloadTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SMSPayload"
     */
    public function testSMSPayload()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "brandID"
     */
    public function testPropertyBrandID()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "numbers"
     */
    public function testPropertyNumbers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "text"
     */
    public function testPropertyText()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "stopList"
     */
    public function testPropertyStopList()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
