<?php

/**
 * SmsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  UBill\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * UBill API
 *
 * UBill API - provides programmatic access to our resources. You will be able to integrate our service into your system and communicate with clients easily.
 *
 * The version of the OpenAPI document: 2.1.8
 * Contact: info@ubill.ge
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace UBill\Sdk\Test\Api;

use UBill\Sdk\Configuration;
use UBill\Sdk\ApiException;
use UBill\Sdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SmsApiTest Class Doc Comment
 *
 * @category Class
 * @package  UBill\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SmsApiTest extends TestCase
{
    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createBrandName
     *
     * Create Brand Name.
     *
     */
    public function testCreateBrandName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDeliveryReport
     *
     * Get Delivery Report.
     *
     */
    public function testGetDeliveryReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSMSBalance
     *
     * Get SMS Balance.
     *
     */
    public function testGetSMSBalance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listBrandNames
     *
     * Get All Brand Names.
     *
     */
    public function testListBrandNames()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for sendSMS
     *
     * Send SMS.
     *
     */
    public function testSendSMS()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
