name: Run Tests and Linter

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-lint:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        php-version:
          - 8.1
          - 8.2
          - 8.3
          - 8.4
          - 8.5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Validate composer.json
        run: composer validate --strict --no-check-version

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run linter
        run: PHP_CS_FIXER_IGNORE_ENV=1 ./vendor/bin/php-cs-fixer check --allow-risky=yes

      - name: Run test suite
        run: ./vendor/bin/phpunit
